### ISSUE TITLE
plugin fails with maven with the error Could not render page content: The following has evaluated to null or missing: [ERROR] ==> output  [in template "scenario-detail.ftl" at line 123, column 55]

### ISSUE THREAD

**Issue by kamomil** [trivago/cluecumber-report-plugin#46] opened 2018-05-21 11:37 UTC
Hi,
I use the plugin with maven,
And I get the error in the title:
`Could not render page content: The following has evaluated to null or missing:
[ERROR] ==> output  [in template "scenario-detail.ftl" at line 123, column 55]`

`[ERROR] Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
[ERROR] ----
[ERROR] 
[ERROR] ----
[ERROR] FTL stack trace ("~" means nesting-related):
[ERROR] 	- Failed at: ${output?html}  [in template "scenario-detail.ftl" at line 123, column 53]
[ERROR] 	~ Reached through: #nested  [in template "macros/page.ftl" in macro "card" at line 31, column 17]
[ERROR] 	~ Reached through: @page.card width="12" title="${elemen...  [in template "scenario-detail.ftl" at line 35, column 5]
[ERROR] 	~ Reached through: #nested  [in template "macros/page.ftl" in macro "page" at line 14, column 13]
[ERROR] 	~ Reached through: @page.page base="../.." links=["tag_s...  [in template "scenario-detail.ftl" at line 5, column 1]
[ERROR] ----
[ERROR] -> [Help 1]`
I can't find the file `scenario-detail.ftl` in my repo or the plugin repo, any help ?
Thanks

**Comment by laxersaz** [comment] 2018-05-21 15:20
This file is located in https://github.com/trivago/cluecumber-report-plugin/tree/master/plugin-code/src/main/resources/template

Could you please send me an example JSON file that causes this error?

**Comment by rvarum** [comment] 2018-05-23 10:16
Hi @laxersaz ,  we managed to fix the root cause of the problem (sorry for not posting a JSON because of security reasons. 
in case we use the Scenario.write() method, and write a null value, it will become "real" null type in the json "output" key. 

i guess the solution will be maybe a validation if the output key contains null (not as string), it will convert into empty string or something.

**Comment by eyalkeren1** [comment] 2018-05-23 10:29
Hey @laxersaz After serious debugging I found the we tried to print a null value variable.
we saw in the JSON that the output value was null (not String).
I also saw that when adding a string before the value then it will work fine (i.e. ("value is " + value) => will print "value null"

**Comment by laxersaz** [comment] 2018-05-23 14:35
@eyalkeren1 thanks a lot for the update - this makes it easier for me to fix it for sure!

**Comment by laxersaz** [comment] 2018-06-10 16:22
This is implemented and will be included in 0.8.0

**Closed by laxersaz** 2018-06-10 16:22 UTC
Labels: bug
